// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mud9Bot.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mud9Bot.Data.Migrations
{
    [DbContext(typeof(BotDbContext))]
    partial class BotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mud9Bot.Data.Entities.BotEventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chat_type");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metadata");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "Metadata", "ChatType")
                        .IsUnique();

                    b.ToTable("bot_event_logs");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.BotGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("groupid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("OffFortune")
                        .HasColumnType("boolean")
                        .HasColumnName("offfortune");

                    b.Property<bool>("OffLomo")
                        .HasColumnType("boolean")
                        .HasColumnName("offlomo");

                    b.Property<bool>("OffSimp")
                        .HasColumnType("boolean")
                        .HasColumnName("offsimp");

                    b.Property<bool>("OffZodiac")
                        .HasColumnType("boolean")
                        .HasColumnName("offzodiac");

                    b.Property<int>("PQuota")
                        .HasColumnType("integer")
                        .HasColumnName("pquota");

                    b.Property<int>("PinnedId")
                        .HasColumnType("integer")
                        .HasColumnName("pinned_id");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegramid");

                    b.Property<DateTime>("TimeAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timeadded");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<int>("WQuota")
                        .HasColumnType("integer")
                        .HasColumnName("wquota");

                    b.Property<long>("Welcome")
                        .HasColumnType("bigint")
                        .HasColumnName("welcome");

                    b.Property<string>("WelcomeGif")
                        .HasColumnType("text")
                        .HasColumnName("welcomegif");

                    b.Property<string>("WelcomePhoto")
                        .HasColumnType("text")
                        .HasColumnName("welcomephoto");

                    b.Property<string>("WelcomeText")
                        .HasColumnType("text")
                        .HasColumnName("welcometext");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("groups");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.BotUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Plastic")
                        .HasColumnType("integer")
                        .HasColumnName("plastic");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegramid");

                    b.Property<DateTime>("TimeAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timeadded");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<int>("Wine")
                        .HasColumnType("integer")
                        .HasColumnName("wine");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.CommandLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Args")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("command_logs");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.CurrencyRate", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision")
                        .HasColumnName("rate");

                    b.Property<double>("RateHkd")
                        .HasColumnType("double precision")
                        .HasColumnName("rate_hkd");

                    b.HasKey("Code");

                    b.ToTable("currency_rates");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.CustomGreeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("GreetingType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("greeting_type");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.HasKey("Id");

                    b.ToTable("custom_greetings");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.DailyLimit", b =>
                {
                    b.Property<int>("LimitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("limitid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LimitId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("groupid");

                    b.Property<int>("PlasticLimit")
                        .HasColumnType("integer")
                        .HasColumnName("plimit");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<int>("WineLimit")
                        .HasColumnType("integer")
                        .HasColumnName("wlimit");

                    b.HasKey("LimitId");

                    b.ToTable("dailylimit");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("DonationId")
                        .HasColumnType("text")
                        .HasColumnName("donationid");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ProviderPaymentChargeId")
                        .HasColumnType("text")
                        .HasColumnName("provider_payment_charge_id");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegramid");

                    b.Property<string>("TelegramPaymentChargeId")
                        .HasColumnType("text")
                        .HasColumnName("telegram_payment_charge_id");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("donation");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.FortuneLimit", b =>
                {
                    b.Property<int>("FortuneLimitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ftid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FortuneLimitId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("groupid");

                    b.Property<DateTime>("LastDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_date");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("msgid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("FortuneLimitId");

                    b.ToTable("fortune_limit");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.GayGif", b =>
                {
                    b.Property<int>("GayGifId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gaygifid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GayGifId"));

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fileid");

                    b.HasKey("GayGifId");

                    b.ToTable("gaygif");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("jobid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobId"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chatid");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_processed");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("msgid");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Recurrence")
                        .HasColumnType("text")
                        .HasColumnName("recurrence");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegramid");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<DateTime>("TimeAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timeadded");

                    b.HasKey("JobId");

                    b.ToTable("job");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.LomoIgnoreWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.ToTable("lomo_ignore_words");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsShowing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_showing");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OnShowDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("on_show_date");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Starring")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("movies");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasColumnType("text")
                        .HasColumnName("setting_key");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("setting_value");

                    b.HasKey("SettingKey");

                    b.ToTable("system_settings");

                    b.HasData(
                        new
                        {
                            SettingKey = "is_maintenance",
                            Description = "Toggle global maintenance mode",
                            LastUpdated = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "false"
                        },
                        new
                        {
                            SettingKey = "maintenance_message",
                            Description = "Message shown to users during maintenance",
                            LastUpdated = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "🛠 系統正在維護中，請稍後再試。 / System is under maintenance. Please try again later."
                        },
                        new
                        {
                            SettingKey = "broadcast_delay_ms",
                            Description = "Delay between messages during global broadcast (ms)",
                            LastUpdated = new DateTime(2026, 2, 24, 9, 51, 31, 565, DateTimeKind.Utc).AddTicks(8530),
                            SettingValue = "35"
                        },
                        new
                        {
                            SettingKey = "web_banner_message",
                            Description = "Site-wide announcement message for the web dashboard",
                            LastUpdated = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = ""
                        },
                        new
                        {
                            SettingKey = "enable_gas",
                            Description = "Feature flag: Enable gas price service",
                            LastUpdated = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "true"
                        },
                        new
                        {
                            SettingKey = "enable_zodiac",
                            Description = "Feature flag: Enable daily zodiac horoscopes",
                            LastUpdated = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "true"
                        },
                        new
                        {
                            SettingKey = "enable_wineplastic",
                            Description = "Feature flag: Enable core wine/plastic interactions",
                            LastUpdated = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingValue = "true"
                        });
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.WinePlastic", b =>
                {
                    b.Property<int>("WinePlasticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wpid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WinePlasticId"));

                    b.Property<int>("Disabled")
                        .HasColumnType("integer")
                        .HasColumnName("disabled");

                    b.Property<DateTime?>("DisabledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disableddate");

                    b.Property<int>("GivenBy")
                        .HasColumnType("integer")
                        .HasColumnName("givenby");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("groupid");

                    b.Property<int>("Plastic")
                        .HasColumnType("integer")
                        .HasColumnName("plastic");

                    b.Property<DateTime>("TimeAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timeadded");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<int>("Wine")
                        .HasColumnType("integer")
                        .HasColumnName("wine");

                    b.HasKey("WinePlasticId");

                    b.ToTable("wineplastic");
                });

            modelBuilder.Entity("Mud9Bot.Data.Entities.Zodiac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerScore")
                        .HasColumnType("integer");

                    b.Property<string>("CareerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("date_key");

                    b.Property<int>("LoveScore")
                        .HasColumnType("integer");

                    b.Property<string>("LoveText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MoneyScore")
                        .HasColumnType("integer");

                    b.Property<string>("MoneyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("OverallText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<int>("ZodiacIndex")
                        .HasColumnType("integer")
                        .HasColumnName("zodiac_index");

                    b.HasKey("Id");

                    b.ToTable("zodiacs");
                });
#pragma warning restore 612, 618
        }
    }
}
